platform :ios, '7.0'

I18n.enforce_available_locales = false

pod 'RaptureXML', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage', '~> 3.5.2'
pod 'RBStoryboardLink', '~> 0.0.8'
pod 'TimesSquare', '~> 1.0.1'
pod 'HMSegmentedControl', '~> 1.3'
pod 'ReactiveCocoa', '~> 2.2.4'
pod 'ReactiveViewModel', '~> 0.2'
pod 'AFNetworking', '~> 2.2'
pod 'CCHMapClusterController', '~> 1.5'

target :MyMenuTests do
	pod 'OCMock', '~> 2.2.3'
end
